spring.application.name=chatonline

server.port=${port:8081}

spring.datasource.url=jdbc:mysql://127.0.0.1:3306/chat_db
spring.datasource.username=ChAtUserTry
spring.datasource.password=PasswordTRyChat

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.servlet.session.timeout= 30m

jwt.secret-key="12332131231381371087sdada"
jwt.access-token.expiration:36000000
jwt.refresh-token.expiration:604800000